apiVersion: v1
kind: Service
metadata:
  name: flask-app
  labels:
    name: flask-app
    app: flask-app
spec:
  selector:
    name: flask-app
  ports:
   - port: 80
     name: http
     targetPort: 80
     protocol: TCP
  type: NodePort
